wandb_version: 1

alpha:
  value: 0.5
batch_size:
  value: 16
epochs:
  value: 10
hidden_Layer_AF:
  value: relu
initializer:
  value: random
learning_rate:
  value: 0.001
loss_func:
  value: mse
n_hidden_layers:
  value: 4
optimizer:
  value: mgd
size_hidden_layers:
  value: 128
