wandb_version: 1

alpha:
  value: 0
batch_size:
  value: 16
epochs:
  value: 10
hidden_Layer_AF:
  value: relu
initializer:
  value: xavier
learning_rate:
  value: 0.001
loss_func:
  value: mse
n_hidden_layers:
  value: 3
optimizer:
  value: adam
size_hidden_layers:
  value: 32
