wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.3
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      4: 3.6.3
      5: 0.10.20
      8:
      - 3
      - 5
alpha:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
hidden_Layer_AF:
  desc: null
  value: sigmoid
initializer:
  desc: null
  value: random
learning_rate:
  desc: null
  value: 0.001
loss_func:
  desc: null
  value: mse
n_hidden_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: sgd
size_hidden_layers:
  desc: null
  value: 64
