wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.3
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      4: 3.6.3
      5: 0.10.20
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0001
n_hidden_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: adam
size_hidden_layers:
  desc: null
  value: 128
