wandb_version: 1

alpha:
  value: 0.5
batch_size:
  value: 32
epochs:
  value: 10
hidden_Layer_AF:
  value: tanh
initializer:
  value: random
learning_rate:
  value: 0.0001
loss_func:
  value: mse
n_hidden_layers:
  value: 3
optimizer:
  value: sgd
size_hidden_layers:
  value: 32
