wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.3
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      4: 3.6.3
      5: 0.10.20
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 16
channels_one:
  desc: null
  value: 16
channels_two:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
n_hidden_layers:
  desc: null
  value: 5
optimizer:
  desc: null
  value: sgd
size_hidden_Layers:
  desc: null
  value: 32
