wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.3
    t:
      1:
      - 2
      - 3
      - 5
      4: 3.6.3
      5: 0.10.20
      8:
      - 3
      - 5
alpha:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 10
hidden_Layer_AF:
  desc: null
  value: relu
initializer:
  desc: null
  value: xavier
learning_rate:
  desc: null
  value: 0.001
loss_func:
  desc: null
  value: mse
n_hidden_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: adam
size_hidden_layers:
  desc: null
  value: 32
