wandb_version: 1

alpha:
  value: 0
batch_size:
  value: 16
epochs:
  value: 10
hidden_Layer_AF:
  value: sigmoid
initializer:
  value: xavier
learning_rate:
  value: 0.001
loss_func:
  value: crossentropy
n_hidden_layers:
  value: 4
optimizer:
  value: nadam
size_hidden_layers:
  value: 64
