wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.3
    t:
      1:
      - 2
      - 3
      - 5
      4: 3.6.3
      5: 0.10.20
      8:
      - 3
      - 5
    visualize:
      conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings: {}
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
alpha:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 10
hidden_Layer_AF:
  desc: null
  value: sigmoid
initializer:
  desc: null
  value: xavier
learning_rate:
  desc: null
  value: 0.001
loss_func:
  desc: null
  value: crossentropy
n_hidden_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: nadam
size_hidden_layers:
  desc: null
  value: 64
